data_set: https://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-red.csv
artifacts:
  artifacts_dir: D:/Interview_prep/dvc/dvc_1/artifacts
  raw_local_dir: D:/Interview_prep/dvc/dvc_1/artifacts/raw_local_dir
  raw_local_file: data.csv
  split_data_dir: D:/Interview_prep/dvc/dvc_1/artifacts/split_data_dir
  train: train.csv
  test: test.csv




